![torchman](imgs/torchman.jpg)

이번 차례에는 머신러닝 파이프라인을 살펴보고 데이터를 어떻게 텐서를 통해 표현하는지 살펴보겠습니다  

# Deep learning pipeline

![dlpl](imgs/pipelin.png)

저희가 지금까지 배운 수 체계에는 스칼라, 벡터, 행렬, 텐서가 있었습니다.  
그리고 많은 머신러닝 책에서는 아래와 같이 표기합니다.  
여러 모듈과 메소드를 통해 파이토치에서 어떻게 텐서를 조작하는지 알아보겠습니다  

[https://pytorch.org/](https://pytorch.org/)

git clone https://github.com/SunCreation/pytorch_master.git

In [3]:
import torch as th

$${스칼라 : x \quad  }$$
$$벡터 : \mathbf x \quad n  $$
$$행렬 : \mathbf X \quad m \times n  $$
$$텐서 : \mathcal {X} \quad l \times m \times n \times \dots $$

먼저 들어가기 앞서서 프로그래밍 초반에 배우는 데이터의 타입을 떠올려보겠습니다.  
대표적으로 다음과 같습니다. 
1. Int  
2. Double  
3. Float  

일반적으로 torch의 여러가지 텐서모듈을 통해 위의 데이터타입을 가지는 텐서를 생성할 수 있습니다 

In [1]:
from torch import tensor
from torch import FloatTensor as ftensor
from torch import DoubleTensor as dtensor

텐서 객체는 다음과 같은 형태로 할당하게 됩니다.  
tensor = tensor(data, dtype=float32, device='cpu')  
텐서 객체를 생성하기 위한 파라미터와 인자는 data, dtype, device가 있습니다.  


## 1. 스칼라

dtype과 device를 지정하지 않으면 자동으로 dtype을 식별하고 device는 cpu로 할당하게 됩니다.   

.item()을 통하여 텐서 객체 내의 단일 스칼라 값을 뽑아낼 수 있습니다. item 메소드는 반드시 스칼라 텐서에서 호출해야 합니다

tensor(3)
torch.int64
cpu
tensor(99.9900)
torch.float32
cpu
tensor(99.9900, dtype=torch.float64)
torch.float64
cpu


## 2. 벡터

In [4]:
import numpy as np

data에 들어갈 수 있는 컨테이너는 List, Tuple, Numpy array입니다.  
파이토치에서 텐서 객체를 만드는 방법은 기존의 numpy와 매우 유사합니다.  

tensor([ 1.0000, -1.1000,  3.9000]) tensor([ 1.0000, -1.1000,  3.9000], dtype=torch.float64) tensor([ 1.0000, -1.1000,  3.9000])


tensor([[[157,  97, 163],
         [121, 182, 158],
         [113,  24, 157],
         ...,
         [162,   7,  53],
         [ 82, 175, 242],
         [185, 176,  19]],

        [[210, 173,  86],
         [ 66, 164,  58],
         [179, 225,  43],
         ...,
         [188,  41,  52],
         [115, 211, 193],
         [ 41,  37, 171]],

        [[118, 141, 131],
         [ 36, 106,  87],
         [105, 208,   7],
         ...,
         [167,  45, 163],
         [ 20, 190, 208],
         [ 66, 150, 208]],

        ...,

        [[ 96,  34,   8],
         [196, 131, 241],
         [176, 213, 125],
         ...,
         [122, 118, 116],
         [165,  25, 201],
         [ 80, 188, 161]],

        [[198,  54, 237],
         [ 96, 153,  38],
         [ 63, 126, 239],
         ...,
         [ 92,  67, 253],
         [  1,  17, 229],
         [184, 142,   5]],

        [[122, 200, 158],
         [244, 198, 146],
         [ 36,  74, 244],
         ...,
         [241, 237,  16],
        

False


[tensor([[[0.6147, 0.3810, 0.6371,  ..., 0.1884, 0.1580, 0.3393],
          [0.3173, 0.4194, 0.0163,  ..., 0.2290, 0.7030, 0.8824],
          [0.1701, 0.1881, 0.2923,  ..., 0.7434, 0.3846, 0.6771],
          ...,
          [0.7768, 0.4471, 0.5403,  ..., 0.0568, 0.2901, 0.4884],
          [0.5162, 0.4743, 0.8506,  ..., 0.6927, 0.0072, 0.7748],
          [0.3817, 0.2500, 0.9313,  ..., 0.4209, 0.8733, 0.2753]],
 
         [[0.2569, 0.1401, 0.8685,  ..., 0.9951, 0.8415, 0.9686],
          [0.6143, 0.3073, 0.9007,  ..., 0.5686, 0.2400, 0.7583],
          [0.9038, 0.1870, 0.3481,  ..., 0.2863, 0.4457, 0.1544],
          ...,
          [0.9716, 0.6627, 0.7946,  ..., 0.9697, 0.3989, 0.5922],
          [0.4969, 0.0662, 0.5834,  ..., 0.4231, 0.2035, 0.5209],
          [0.2005, 0.6369, 0.5223,  ..., 0.5853, 0.3580, 0.2340]],
 
         [[0.5736, 0.2327, 0.7737,  ..., 0.2778, 0.0203, 0.7147],
          [0.9550, 0.4341, 0.4158,  ..., 0.6765, 0.5589, 0.2580],
          [0.7581, 0.4183, 0.6897,  ...,

[tensor([[[0.6147, 0.3810, 0.6371,  ..., 0.1884, 0.1580, 0.3393],
          [0.3173, 0.4194, 0.0163,  ..., 0.2290, 0.7030, 0.8824],
          [0.1701, 0.1881, 0.2923,  ..., 0.7434, 0.3846, 0.6771],
          ...,
          [0.7768, 0.4471, 0.5403,  ..., 0.0568, 0.2901, 0.4884],
          [0.5162, 0.4743, 0.8506,  ..., 0.6927, 0.0072, 0.7748],
          [0.3817, 0.2500, 0.9313,  ..., 0.4209, 0.8733, 0.2753]],
 
         [[0.2569, 0.1401, 0.8685,  ..., 0.9951, 0.8415, 0.9686],
          [0.6143, 0.3073, 0.9007,  ..., 0.5686, 0.2400, 0.7583],
          [0.9038, 0.1870, 0.3481,  ..., 0.2863, 0.4457, 0.1544],
          ...,
          [0.9716, 0.6627, 0.7946,  ..., 0.9697, 0.3989, 0.5922],
          [0.4969, 0.0662, 0.5834,  ..., 0.4231, 0.2035, 0.5209],
          [0.2005, 0.6369, 0.5223,  ..., 0.5853, 0.3580, 0.2340]],
 
         [[0.5736, 0.2327, 0.7737,  ..., 0.2778, 0.0203, 0.7147],
          [0.9550, 0.4341, 0.4158,  ..., 0.6765, 0.5589, 0.2580],
          [0.7581, 0.4183, 0.6897,  ...,

## 3. 행렬

이제 행렬 텐서를 만들어보겠습니다.  
데이터타입을 행렬로 다루기 시작한다면 device를 gpu로 지정하는게 좋습니다.  
이제 데이터를 일일히 생성하기 힘드므로 rand를 사용하겠습니다.  
rand를 잘 활용하기 위해 시드를 고정하겠습니다.  

![tensor](imgs/tensor.png)

## 4. 텐서  
이제 3차원 이상의 텐서를 만들어보겠습니다.  

# 퀴즈 (Easy)  
1) !nvidia-smi 를 통해 현재 gpu의 메모리 사용량을 확인하세요
2) 크기가 (100, 100, 100)인 3차원 랜덤 텐서를 gpu 메모리에 할당하세요
3) 다시 !nvidia-smi를 통해 gpu 메모리 사용량이 얼마나 늘었는지 계산해보세요

In [ ]:
!nvidia-smi

# 5. 텐서의 연산


tensor(32)

tensor([-3,  6, -3])


tensor([ 4, 10, 18])


tensor([[ 5, 12],
        [21, 32]])


tensor([[19, 22],
        [43, 50]])