 ## 5. 텐서의 연산

파이토치에서 다루는 모든 벡터, 행렬, 텐서들에 대해서  
덧셈, 뺄셈, 내적, 외적을 할 수 있습니다.  

In [1]:
import torch as th
from torch import tensor

## 6. 텐서 차원 조작  *** 중요!!! ***
딥러닝 모델에 데이터를 입력하기 위해 텐서의 차원을 정말 잘 다루어야 합니다.   
이때 차원을 조작하는 메소드로는 다음과 같습니다. # flatten(), reshape(), view()가 있습니다. 
1) 차원 축소, 확장 :  squeeze(), unsqueeze()  
2) 차원 교환 : transpose(), permute()  # 순서를 바꾸다.
3) 차원 조정 : flatten(), view() reshape()  
4) 텐서 합성 및 적재 : cat() stack()  

### 6.1 차원 축소, 확장 :  squeeze(), unsqueeze()  

In [2]:
# torch.ones(shape)를 통해 모든값이 1인 텐서를 쉽게 만들수 있다.
tensor_7d = th.ones([10,32,1,1,64,64,3])
tensor_7d_0 = th.zeros([10,32,1,1,64,64,3])

tensor_7d_1 = th.ones_like(tensor_7d)
tensor_7d_2 = th.zeros_like(tensor_7d_0)


In [6]:
v = th.randn(4)
diag_tensor = th.diag(v)
norm_tensor = th.norm(diag_tensor)
print(diag_tensor,norm_tensor)

tensor([[-1.7658,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.3852,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.3332,  0.0000],
        [ 0.0000,  0.0000,  0.0000, -0.1831]]) tensor(1.8469)


In [7]:
# torch.squeeze(axis) 함수는 차윈의 크기가 1인 특정 축을 제거합니다.
# axis 값이 없으면 모든 축을 제거합니다.

tensor_6d = tensor_7d.squeeze(axis=2)
print(tensor_6d)
tensor_5d = tensor_7d.squeeze()
print(tensor_5d.shape)

tensor([[[[[[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           ...,

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.]],

           [[1., 1., 1.],
            [1., 1., 1.],
            [1., 1., 1.],
            ...,
            [

In [11]:
# torch.unsqueeze(axis=m) : 차원의 크기가 1인 축을 m번째 인덱스에 추가합니다.
# axis 값이 없으면 어디에 추가될까요?

# 퀴즈 : 0번째 인덱스에 잉여차원을 추가하세요.

tensor_5d = th.ones([3,3,4,1,5])
tensor_6d_1 = tensor_5d.unsqueeze(0)
tensor_6d_1.shape

torch.Size([1, 3, 3, 4, 1, 5])

### 6.2 차원 교환 : transpose(), permute()  
위 메소드들은 주로 데이터를 변환할 때 많이 사용합니다.  


In [12]:
matrix =  th.ones([2,3])
print(matrix.shape)

torch.Size([2, 3])


In [15]:
# torch.transpose(input, dim0,dim1)
transposed = th.transpose(matrix, 0,1)
print(transposed.shape)

torch.Size([3, 2])


In [16]:
transposed_2 = matrix.transpose(0,1)
print(transposed_2.shape)

torch.Size([3, 2])


In [17]:
tensor_4d = th.ones([4,2,6,1])
# 퀴즈 : 0번째, 2번째 차원을 교환하세요.

transposed_4d = tensor_4d.transpose(0,2)
print(transposed_4d.shape)

torch.Size([6, 2, 4, 1])


In [18]:
# torch.permute() : transpose 의 상위버전 메소드, 차원 축 순서를 원하는 대로 나열하낟.

permuted_4d = th.permute(tensor_4d, (2, 0, 1, 3))
print(permuted_4d.shape)    

torch.Size([6, 4, 2, 1])


In [19]:
flattened_t = th.flatten(permuted_4d, start_dim=1)
print(flattened_t.shape) 

torch.Size([6, 8])


In [20]:
# np.argsort
t2 = th.arange(36)

print(t2.shape)
t2.reshape(4,9)

torch.Size([36])


tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [28]:
t3 = th.arange(24940)
viewed_t1 = t3.reshape(5,4,-1)
print(viewed_t1.shape)
viewed_t2 = t3.view(5,4,-1)
print(viewed_t2.shape)
# 무슨차이?? view가 깊은 복사라는데
print(t3.shape)
viewed_t1[:,:,-1] = 0
print(viewed_t1[:,:,-1])
print(t3[-1249:])

torch.Size([5, 4, 1247])
torch.Size([5, 4, 1247])
torch.Size([24940])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([23691,     0, 23693,  ..., 24937, 24938,     0])


In [36]:
vec1 = tensor([[1],[2],[3]])
vec2 = tensor([[4],[5],[6]])
vec3 = tensor([[7],[8],[9]])
vec4 = th.cat([vec1,vec2,vec3],dim=1)
print(vec4)

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


In [30]:
vec5 = th.stack([vec1,vec2,vec3], dim=0)
print(vec5)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


### 6.3 차원 조정 : flatten(),  reshape(), view()  
위 세 가지 메소드는 주로 CNN 레이어에서 FC 레이어로 오고 갈 때 자주 사용합니다.  

### 6.4 텐서 합성 및 적재 : cat() stack()  
마지막으로 텐서를 합성하기 위해 cat()과 stack()을 활용합니다.  
cat() 함수는 모델 내부에서 다음 은닉층에 들어가는 텐서들을 조합하기 위해 주로 사용합니다.  

stack() 함수는 데이터를 쌓아서 미니배치를 구성할 때 주로 사용합니다.  

In [ ]:
th.mean()
th.sum()
th.min()
th.argmin()
th.max()
th.argmax()

# 퀴즈 (Hard)
1) 길이가 4096인 랜덤벡터를 하나 생성하세요.  
2) 벡터를 위에서 배운 메소드들 중 하나를 이용해 (64x64) 정사각행렬로 차원을 조정하세요. 
3) 1, 2의 과정을 반복해서 정사각행렬을 세 개 만든다음, 각각 텐서의 0번째 축에 크기가 1인 잉여차원을 추가하세요.  
4) 0번째 축과 마지막 축을 교환하세요.   
5) 리스트에 세 개의 정사각행렬을 담아서 마지막 축을 기준으로 텐서를 합성하세요 -> 64x64x3 텐서가 나와야함  
6) 위의 과정을 4번 반복해서 64x64x3 를 쌓아서 4 x 64 x 64 x 3 텐서를 만드세요  

In [39]:
th.manual_seed(1030)
# code : 
t_dim1_1 = th.randn(4096)
t_dim2_1,t_dim2_2,t_dim2_3 = [th.unsqueeze(th.randn(4096).reshape(64,64), dim=0).transpose(0,-1) for i in range(3)]
t_dim2_4,t_dim2_5,t_dim2_6 = [th.unsqueeze(th.randn(4096).reshape(64,64), dim=0).transpose(0,-1) for i in range(3)]
t_dim2_7,t_dim2_8,t_dim2_9 = [th.unsqueeze(th.randn(4096).reshape(64,64), dim=0).transpose(0,-1) for i in range(3)]
t_dim2_10,t_dim2_11,t_dim2_12 = [th.unsqueeze(th.randn(4096).reshape(64,64), dim=0).transpose(0,-1) for i in range(3)]

concat_T1 = th.cat([t_dim2_1,t_dim2_2,t_dim2_3],dim=2)
concat_T2 = th.cat([t_dim2_4,t_dim2_5,t_dim2_6],dim=2)
concat_T3 = th.cat([t_dim2_7,t_dim2_8,t_dim2_9],dim=2)
concat_T4 = th.cat([t_dim2_10,t_dim2_11,t_dim2_12],dim=2)
print(concat_T1.shape)
final_t = th.stack([concat_T1,concat_T2,concat_T3,concat_T4])
final_t.shape



torch.Size([64, 64, 3])


torch.Size([4, 64, 64, 3])